# docker-compose.yml
version: '3.8'

services:
  app:
    build: .
    ports:
      - "8011:8011"
    depends_on:
      - db
    environment:
      - MYSQL_USER=taskapi
      - MYSQL_PASSWORD=taskpassword
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_DB=task_management
      - SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
    volumes:
      - ./:/app
    restart: always

  db:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=task_management
      - MYSQL_USER=taskapi
      - MYSQL_PASSWORD=taskpassword
      - MYSQL_ROOT_PASSWORD=rootpassword
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data: